services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/nianokia/wc-consulting.git
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wcc
          property: connectionString
databases:
  - name: db
    plan: free
    ipAllowList: []
